version: '2'
services:
  ide:
    image: akkaidea
    environment:
      - DISPLAY=novnc:0.0
    depends_on:
      - novnc
    volumes:
      - .:/scala/akkacrawl
    networks:
      - x11
  novnc:  
    image: psharkey/novnc:latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=600
    ports:
      - "8080:8080"
    networks:
      - x11
networks:
  x11: